<section class="mx-auto max-w-4xl space-y-6">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p class="text-sm font-bold text-rose-800">نوع ورد</p><h1 class="mt-1 text-2xl font-bold text-slate-950">{{ $product->name }}</h1><p class="mt-1 font-mono text-sm text-slate-600">{{ $product->code }}</p></div><div class="flex flex-wrap gap-2"><a wire:navigate href="{{ route('flowers.inventory.movements', $product) }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-bold text-slate-700">حركة الورد</a><a wire:navigate href="{{ route('flowers.inventory.receipt-age', $product) }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-bold text-slate-700">سجل الوصول</a>@can('manage-flower-master-data')<a wire:navigate href="{{ route('flowers.products.edit', $product) }}" class="rounded-lg bg-rose-600 px-4 py-2 text-sm font-bold text-white">تعديل</a>@endcan</div></div>
    <div class="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-2 lg:grid-cols-3"><div><p class="text-xs font-bold text-slate-500">الرصيد الحالي</p><p class="mt-1 text-3xl font-bold text-slate-950">{{ $product->current_quantity }}</p><p class="text-xs text-slate-500">{{ $product->unit }}</p></div><div><p class="text-xs font-bold text-slate-500">اللون / الدرجة</p><p class="mt-1 font-bold">{{ collect([$product->color, $product->grade])->filter()->join(' · ') ?: '—' }}</p></div><div><p class="text-xs font-bold text-slate-500">الحد الأدنى</p><p class="mt-1 font-bold">{{ $product->minimum_quantity ?? '—' }}</p></div><div><p class="text-xs font-bold text-slate-500">سعر الشراء</p><p class="mt-1 font-bold">{{ $product->purchase_price ?? '—' }}</p></div><div><p class="text-xs font-bold text-slate-500">سعر البيع</p><p class="mt-1 font-bold">{{ $product->sale_price ?? '—' }}</p></div><div><p class="text-xs font-bold text-slate-500">الحالة</p><p class="mt-1 font-bold">{{ $product->is_active ? 'نشط' : 'غير نشط' }}</p></div><div class="sm:col-span-2 lg:col-span-3"><p class="text-xs font-bold text-slate-500">ملاحظات</p><p class="mt-1 whitespace-pre-line text-sm text-slate-700">{{ $product->notes ?? '—' }}</p></div></div>
    @can('register-flower-opening-stock')
        @if($product->current_quantity === '0.000' && ! $product->stockMovements()->exists())
            <a wire:navigate href="{{ route('flowers.products.opening', $product) }}" class="inline-flex rounded-lg border border-rose-300 bg-rose-50 px-4 py-2.5 text-sm font-bold text-rose-800">تسجيل رصيد افتتاحي</a>
        @endif
    @endcan
</section>
