<section class="space-y-6">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm font-bold text-amber-800">فواتير البيع</p><h1 class="mt-1 text-2xl font-bold text-slate-950">سجل فواتير السلامي</h1></div><a wire:navigate href="{{ route('salami.invoices.create') }}" class="rounded-lg bg-amber-500 px-4 py-2.5 text-sm font-bold text-amber-950">فاتورة جديدة</a></div>
    <div class="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-7">
        <input wire:model.live.debounce.300ms="search" type="search" placeholder="رقم الفاتورة" class="rounded-lg border-slate-300 text-sm">
        <select wire:model.live="status" class="rounded-lg border-slate-300 text-sm"><option value="">كل الحالات</option><option value="draft">مسودة</option><option value="confirmed">معتمدة</option><option value="cancelled">ملغاة</option></select>
        <select wire:model.live="paymentStatus" class="rounded-lg border-slate-300 text-sm"><option value="">كل حالات السداد</option><option value="paid">مسددة</option><option value="partial">جزئية</option><option value="unpaid">غير مسددة</option></select>
        <select wire:model.live="customerId" class="rounded-lg border-slate-300 text-sm"><option value="">كل المحلات</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }}</option>@endforeach</select>
        <select wire:model.live="deliveryAgentId" class="rounded-lg border-slate-300 text-sm"><option value="">كل المناديب</option>@foreach($deliveryAgents as $deliveryAgent)<option value="{{ $deliveryAgent->id }}">{{ $deliveryAgent->name }}</option>@endforeach</select>
        <input wire:model.live="from" type="date" class="rounded-lg border-slate-300 text-sm">
        <input wire:model.live="to" type="date" class="rounded-lg border-slate-300 text-sm">
    </div>
    <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-right"><thead class="bg-slate-50 text-xs font-bold text-slate-500"><tr><th class="px-4 py-3">رقم الفاتورة</th><th class="px-4 py-3">التاريخ</th><th class="px-4 py-3">المحل</th><th class="px-4 py-3">المندوب</th><th class="px-4 py-3">الحالة</th><th class="px-4 py-3">السداد</th><th class="px-4 py-3">الإجمالي</th><th class="px-4 py-3">المدفوع</th><th class="px-4 py-3">المتبقي</th><th class="px-4 py-3">أنشأها</th></tr></thead><tbody class="divide-y divide-slate-100 text-sm">@forelse($invoices as $invoice)<tr><td class="px-4 py-3 font-mono font-bold"><a wire:navigate href="{{ route('salami.invoices.show',$invoice) }}" class="hover:text-amber-700">{{ $invoice->invoice_number }}</a></td><td class="px-4 py-3 text-slate-600">{{ $invoice->invoice_date->format('Y-m-d') }}</td><td class="px-4 py-3 font-bold text-slate-700">{{ $invoice->customer->name }}</td><td class="px-4 py-3 text-slate-600">{{ $invoice->deliveryAgent?->name ?? '—' }}</td><td class="px-4 py-3"><span @class(['rounded-full px-2.5 py-1 text-xs font-bold','bg-amber-100 text-amber-800'=>$invoice->status->value==='draft','bg-emerald-100 text-emerald-800'=>$invoice->status->value==='confirmed','bg-rose-100 text-rose-800'=>$invoice->status->value==='cancelled'])>{{ $invoice->status->value==='draft'?'مسودة':($invoice->status->value==='confirmed'?'معتمدة':'ملغاة') }}</span></td><td class="px-4 py-3">{{ $invoice->payment_status->value==='paid'?'مسددة':($invoice->payment_status->value==='partial'?'جزئية':'غير مسددة') }}</td><td class="px-4 py-3 font-bold">{{ $invoice->total_amount }}</td><td class="px-4 py-3">{{ $invoice->paid_amount }}</td><td class="px-4 py-3">{{ $invoice->remaining_amount }}</td><td class="px-4 py-3 text-slate-600">{{ $invoice->createdBy->name }}</td></tr>@empty<tr><td colspan="10" class="px-4 py-10 text-center text-sm text-slate-500">لا توجد فواتير مطابقة.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 px-4 py-3">{{ $invoices->links() }}</div></div>
</section>
