<section class="space-y-6">
    <div class="rounded-2xl border border-rose-200 bg-gradient-to-l from-rose-50 to-white p-6 sm:p-8"><p class="text-sm font-bold text-rose-800">إدارة مخزون الورد</p><h1 class="mt-2 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">ملخص التشغيل اليومي</h1><p class="mt-2 text-sm leading-7 text-slate-600">مؤشرات الوصول والتالف والخروج غير البيعي من السجل التشغيلي.</p><div class="mt-5 flex flex-wrap gap-3">
            @can('operate-flower-receipts')
                <a wire:navigate href="{{ route('flowers.receipts.create') }}" class="rounded-lg bg-rose-600 px-4 py-2.5 text-sm font-bold text-white">إضافة مخزون</a>
            @endcan
            @can('operate-flower-exits')
                <a wire:navigate href="{{ route('flowers.exits.create') }}" class="rounded-lg border border-rose-300 bg-white px-4 py-2.5 text-sm font-bold text-rose-900">خروج ورد</a>
            @endcan
        </div></div>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-bold text-slate-500">الأنواع النشطة</p><p class="mt-2 text-3xl font-bold">{{ $activeProductCount }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-bold text-slate-500">إجمالي الرصيد الحالي</p><p class="mt-2 text-3xl font-bold">{{ $totalCurrentQuantity }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-bold text-slate-500">المستلم اليوم</p><p class="mt-2 text-3xl font-bold text-emerald-700">{{ $quantityReceivedToday }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-bold text-slate-500">المقبول اليوم</p><p class="mt-2 text-3xl font-bold text-emerald-700">{{ $acceptedQuantityToday }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-bold text-slate-500">نقص الوصول اليوم</p><p class="mt-2 text-3xl font-bold text-rose-700">{{ $shortageToday }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-bold text-slate-500">تالف عند الوصول اليوم</p><p class="mt-2 text-3xl font-bold text-rose-700">{{ $arrivalDamageToday }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-bold text-slate-500">تالف بعد التخزين اليوم</p><p class="mt-2 text-3xl font-bold text-rose-700">{{ $wasteToday }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-bold text-slate-500">خروج يدوي اليوم</p><p class="mt-2 text-3xl font-bold text-rose-700">{{ $manualExitsToday }}</p></div><div class="rounded-2xl border border-rose-200 bg-rose-50 p-5"><p class="text-sm font-bold text-rose-800">نفد أو منخفض</p><p class="mt-2 text-3xl font-bold text-rose-950">{{ $lowStockProductCount }}</p></div></div>
    <div class="grid gap-6 lg:grid-cols-2"><div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 class="font-bold text-slate-950">تنبيه المخزون</h2><a wire:navigate href="{{ route('flowers.inventory.index',['stockStatus'=>'low']) }}" class="text-sm font-bold text-rose-800">المخزون الحالي</a></div><div class="divide-y divide-slate-100">@forelse($lowStockProducts as $product)<a wire:navigate href="{{ route('flowers.inventory.movements',$product) }}" class="flex items-center justify-between px-5 py-4 hover:bg-slate-50"><span><span class="block font-bold">{{ $product->name }}</span><span class="mt-1 block text-xs text-slate-500">{{ $product->color ?? '—' }} · {{ $product->unit }}</span></span><span class="text-lg font-bold text-rose-700">{{ $product->current_quantity }}</span></a>@empty<p class="px-5 py-8 text-center text-sm text-slate-500">كل الأنواع ضمن المستويات الطبيعية.</p>@endforelse</div></div><div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 class="font-bold text-slate-950">آخر الاستلامات</h2><a wire:navigate href="{{ route('flowers.receipts.index') }}" class="text-sm font-bold text-rose-800">كل الاستلامات</a></div><div class="divide-y divide-slate-100">@forelse($latestReceipts as $receipt)<a wire:navigate href="{{ route('flowers.receipts.show',$receipt) }}" class="flex items-center justify-between px-5 py-4 hover:bg-slate-50"><span><span class="block font-mono font-bold">{{ $receipt->receipt_number }}</span><span class="mt-1 block text-xs text-slate-500">{{ $receipt->supplier->name }} · {{ $receipt->receipt_date->format('Y-m-d') }}</span></span><span class="text-xs font-bold {{ $receipt->status->value === 'confirmed' ? 'text-emerald-700' : 'text-rose-700' }}">{{ $receipt->status->value === 'confirmed' ? 'معتمد' : 'مسودة' }}</span></a>@empty<p class="px-5 py-8 text-center text-sm text-slate-500">لا توجد استلامات بعد.</p>@endforelse</div></div></div>
    <div class="grid gap-6 lg:grid-cols-2"><div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 class="font-bold text-slate-950">آخر التالف</h2><a wire:navigate href="{{ route('flowers.waste.index') }}" class="text-sm font-bold text-rose-800">السجل</a></div><div class="divide-y divide-slate-100">@forelse($latestWastes as $waste)<div class="flex items-center justify-between px-5 py-4"><span><span class="block font-bold">{{ $waste->stockable->name }}</span><span class="mt-1 block text-xs text-slate-500">{{ $waste->reason }} · {{ $waste->waste_date->format('Y-m-d') }}</span></span><span class="font-bold text-rose-700">{{ $waste->quantity }}</span></div>@empty<p class="px-5 py-8 text-center text-sm text-slate-500">لا يوجد تالف مسجل بعد.</p>@endforelse</div></div><div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 class="font-bold text-slate-950">آخر الخروج اليدوي</h2><a wire:navigate href="{{ route('flowers.exits.index') }}" class="text-sm font-bold text-rose-800">السجل</a></div><div class="divide-y divide-slate-100">@forelse($latestExits as $exit)<div class="flex items-center justify-between px-5 py-4"><span><span class="block font-bold">{{ $exit->product->name }}</span><span class="mt-1 block text-xs text-slate-500">{{ $exit->exit_date->format('Y-m-d') }} · {{ $exit->recipient_name ?? 'بدون اسم مستلم' }}</span></span><span class="font-bold text-rose-700">{{ $exit->quantity }}</span></div>@empty<p class="px-5 py-8 text-center text-sm text-slate-500">لا توجد عمليات خروج بعد.</p>@endforelse</div></div></div>
</section>
