<section class="space-y-6">
    <div class="rounded-2xl border border-rose-200 bg-rose-50/70 p-6 sm:p-7"><p class="app-eyebrow">إدارة مخزون الورد</p><h1 class="app-title">ملخص التشغيل اليومي</h1><p class="app-description">مؤشرات الوصول والتالف والخروج غير البيعي من السجل التشغيلي.</p><div class="mt-5 flex flex-wrap gap-3">@can('operate-flower-receipts')<a wire:navigate href="{{ route('flowers.receipts.create') }}" class="app-button app-button-primary">إضافة مخزون</a>@endcan @can('operate-flower-exits')<a wire:navigate href="{{ route('flowers.exits.create') }}" class="app-button app-button-secondary">خروج ورد</a>@endcan @can('operate-flower-invoices')<a wire:navigate href="{{ route('flowers.invoices.create') }}" class="app-button app-button-secondary">فاتورة ورد جديدة</a>@endcan</div></div>
    <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">
        @foreach ([['الأنواع النشطة', $activeProductCount, ''], ['إجمالي الرصيد الحالي', $totalCurrentQuantity, ''], ['المستلم اليوم', $quantityReceivedToday, 'text-emerald-700'], ['المقبول اليوم', $acceptedQuantityToday, 'text-emerald-700'], ['نقص الوصول اليوم', $shortageToday, 'text-red-700'], ['تالف عند الوصول اليوم', $arrivalDamageToday, 'text-red-700'], ['تالف بعد التخزين اليوم', $wasteToday, 'text-red-700'], ['خروج يدوي اليوم', $manualExitsToday, 'text-red-700']] as [$label, $value, $color])
            <div class="app-metric"><p class="app-metric-label">{{ $label }}</p><p class="app-metric-value {{ $color }}">@quantity($value)</p></div>
        @endforeach
        <div class="app-metric border-rose-200 bg-rose-50"><p class="app-metric-label text-rose-800">نفد أو منخفض</p><p class="app-metric-value text-rose-950">{{ $lowStockProductCount }}</p></div>
    </div>
    <div class="grid gap-6 lg:grid-cols-2">
        <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 class="font-semibold">تنبيه المخزون</h2><a wire:navigate href="{{ route('flowers.inventory.index', ['stockStatus' => 'low']) }}" class="text-sm font-semibold text-rose-800">المخزون الحالي</a></div><div class="divide-y divide-slate-100">@forelse($lowStockProducts as $product)<a wire:navigate href="{{ route('flowers.inventory.movements', $product) }}" class="flex items-center justify-between px-5 py-4 hover:bg-slate-50"><span><span class="block font-semibold">{{ $product->name }}</span><span class="mt-1 block text-xs text-slate-500">{{ $product->color ?? '—' }} · {{ $product->unit }}</span></span><span class="text-lg font-bold text-red-700">@quantity($product->current_quantity)</span></a>@empty<p class="app-empty">كل الأنواع ضمن المستويات الطبيعية.</p>@endforelse</div></div>
        <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 class="font-semibold">آخر الاستلامات</h2><a wire:navigate href="{{ route('flowers.receipts.index') }}" class="text-sm font-semibold text-rose-800">عرض الكل</a></div><div class="divide-y divide-slate-100">@forelse($latestReceipts as $receipt)<a wire:navigate href="{{ route('flowers.receipts.show', $receipt) }}" class="flex items-center justify-between px-5 py-4 hover:bg-slate-50"><span><span class="block font-mono font-semibold">{{ $receipt->receipt_number }}</span><span class="mt-1 block text-xs text-slate-500">{{ $receipt->supplier->name }} · {{ $receipt->receipt_date->format('Y-m-d') }}</span></span><span class="app-badge {{ $receipt->status->value === 'confirmed' ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800' }}">{{ $receipt->status->value === 'confirmed' ? 'معتمد' : 'مسودة' }}</span></a>@empty<p class="app-empty">لا توجد استلامات حتى الآن.</p>@endforelse</div></div>
    </div>
    <div class="grid gap-6 lg:grid-cols-2">
        <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 class="font-semibold">آخر التالف</h2><a wire:navigate href="{{ route('flowers.waste.index') }}" class="text-sm font-semibold text-rose-800">السجل</a></div><div class="divide-y divide-slate-100">@forelse($latestWastes as $waste)<div class="flex items-center justify-between px-5 py-4"><span><span class="block font-semibold">{{ $waste->stockable->name }}</span><span class="mt-1 block text-xs text-slate-500">{{ $waste->reason }} · {{ $waste->waste_date->format('Y-m-d') }}</span></span><span class="font-semibold text-red-700">@quantity($waste->quantity)</span></div>@empty<p class="app-empty">لا يوجد تالف مسجل حتى الآن.</p>@endforelse</div></div>
        <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 class="font-semibold">آخر الخروج اليدوي</h2><a wire:navigate href="{{ route('flowers.exits.index') }}" class="text-sm font-semibold text-rose-800">السجل</a></div><div class="divide-y divide-slate-100">@forelse($latestExits as $exit)<div class="flex items-center justify-between px-5 py-4"><span><span class="block font-semibold">{{ $exit->product->name }}</span><span class="mt-1 block text-xs text-slate-500">{{ $exit->exit_date->format('Y-m-d') }} · {{ $exit->recipient_name ?? 'بدون اسم مستلم' }}</span></span><span class="font-semibold text-red-700">@quantity($exit->quantity)</span></div>@empty<p class="app-empty">لا توجد عمليات خروج حتى الآن.</p>@endforelse</div></div>
    </div>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><div class="app-metric"><p class="app-metric-label">الكمية المباعة اليوم</p><p class="app-metric-value text-red-700">@quantity($quantitySoldToday)</p></div><div class="app-metric"><p class="app-metric-label">فواتير اليوم المعتمدة</p><p class="app-metric-value">{{ $invoiceCountToday }}</p></div><div class="app-metric"><p class="app-metric-label">قيمة مبيعات اليوم</p><p class="app-metric-value">@money($salesValueToday)</p></div></div>
    <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 class="font-semibold">آخر الفواتير</h2><a wire:navigate href="{{ route('flowers.invoices.index') }}" class="text-sm font-semibold text-rose-800">السجل</a></div><div class="divide-y divide-slate-100">@forelse($latestInvoices as $invoice)<a wire:navigate href="{{ route('flowers.invoices.show', $invoice) }}" class="flex items-center justify-between px-5 py-4 hover:bg-slate-50"><span><span class="block font-mono font-semibold">{{ $invoice->invoice_number }}</span><span class="mt-1 block text-xs text-slate-500">{{ $invoice->recipient_name ?? 'بدون مستلم' }} · {{ $invoice->invoice_date->format('Y-m-d') }}</span></span><span class="font-semibold">@money($invoice->total_amount)</span></a>@empty<p class="app-empty">لا توجد فواتير حتى الآن.</p>@endforelse</div></div>
</section>
